/// <reference types="astro/client" />
/// <reference path="../worker-configuration.d.ts" />

/**
 * Secrets used by /do-i-work.
 *
 * `worker-configuration.d.ts` is generated by `wrangler types` and declares an
 * empty `Cloudflare.Env` (correctly — secrets are never listed in
 * wrangler.jsonc). This augments it by interface merging, so the two values are
 * documented and type-checked in the repo while their contents stay out of it.
 *
 * Rerun `npx wrangler types` after changing wrangler.jsonc.
 */
declare namespace Cloudflare {
  interface Env {
    /** Shared password handed out by J&L for the "Do I Work" page. */
    DO_I_WORK_PASSWORD: string;
    /** Independent key used to sign the session cookie. Not the password. */
    AUTH_SECRET: string;
  }
}

/** The same two values as seen through Vite, for local `astro dev`. */
interface ImportMetaEnv {
  readonly DO_I_WORK_PASSWORD?: string;
  readonly AUTH_SECRET?: string;
}

interface ImportMeta {
  readonly env: ImportMetaEnv;
}
